version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key-change-this}
      - DATABASE_URL=postgresql://retroai:password@db:5432/retroai
    command: sh -c "npx prisma migrate deploy && node server.js"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .env:/app/.env  # Mount environment file
    networks:
      - retro-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=retroai
      - POSTGRES_USER=retroai
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/schema.prisma:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U retroai -d retroai"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - retro-network

volumes:
  postgres_data:

networks:
  retro-network:
    driver: bridge