version: '3.8'

services:
  app:
    build: .
    container_name: retro-ai-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://retroai:password@db:5432/retroai
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-change-in-production
    depends_on:
      - db
    command: sh -c "npx prisma migrate dev && npm run dev"

  db:
    image: postgres:15-alpine
    container_name: retro-ai-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=retroai
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=retroai
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: