version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://retroai:password@db:5432/retroai
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=development-secret-change-in-production
    networks:
      - retro-network

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: retroai
      POSTGRES_PASSWORD: password
      POSTGRES_DB: retroai
    networks:
      - retro-network

volumes:
  postgres-data:

networks:
  retro-network: